config/routes.rb
Tweetsearch::Application.routes.draw do

  root 'searches#new'

  resources :searches, only: [:create, :show]

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def new
  end

  def create
    term = params[:search][:search_term]
    term = term.gsub(/^#(.*)/, '\1')
    redirect_to search_path(term)
  end

  def show
    term = '#' + params[:id]
    @search_term = term
    @results = Twitter.search(term).results
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tweetsearch</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/searches/new.html.erb
<h1> search twitter here </h1>

<%= form_for :search, url: searches_path do |f| %>
  <%= f.label :search_term %>
  <%= f.text_field :search_term, {:class => "search_term"} %>
  <%= f.submit 'Submit' %>
<% end %>

app/views/searches/show.html.erb
<ul>
<% @results.each do |result| %>
  <li class='result'>
  <%= result.text %>
  </li>
<% end %>
</ul>

<!-- refactor me!!! -->
<%= form_for :search, url: searches_path do |f| %>
  <%= f.label :search_term %>
  <%= f.text_field :search_term, {:value => @search_term, :class => "search_term"} %>
  <%= f.submit 'Submit' %>
<% end %>